### PR TITLE
Add code formatter

### PR DESCRIPTION
**Pull request by jaxx2104**
## Description

This PR add automated code formatting with [Prettier](https://prettier.io/).
and eslint is devDependencies pulled up to the root of a monorepo.
https://github.com/lerna/lerna#common-devdependencies

## Types of changes

- [x] Add prettier
- [x] Pulled up to the root eslint
- [x] `npm run format`
- [x] `npm audit fix`

### CODE REVIEW

**Comment by AtomicBlom** [comment]
Oops, sorry, I've noticed this PR, but it killed chrome in my phone when I tried to look at it. Will try again in my desktop tomorrow morning.

**Comment by AtomicBlom** [comment]
Thank you so much for contributing to the project, and I'd love to bring this in, however I personally have a preference for indenting with tabs, could we please update PR?

**Comment by jaxx2104** [comment]
Nice tools! Update `tab width` is 4.
Should I also enable the `use tabs` option?

**Comment by AtomicBlom** [comment]
Yes please :)

Happy to bring this in after that

**Comment by jaxx2104** [comment]
Update `use tabs` :)

**Comment by AtomicBlom** [comment]
Awesome! Thanks so much!

**Pull request merged**
